-- phpMyAdmin SQL Dump
-- version 4.9.3
-- https://www.phpmyadmin.net/
--
-- Hôte : localhost:3306
-- Généré le :  ven. 27 nov. 2020 à 11:24
-- Version du serveur :  5.7.26
-- Version de PHP :  7.4.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Base de données :  `agriandco`
--

-- --------------------------------------------------------

--
-- Structure de la table `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `title_href` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `img` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `articles`
--

INSERT INTO `articles` (`id`, `title`, `title_href`, `content`, `img`, `created_at`) VALUES
(1, 'Sainte-Anne-sur-Vilaine. Camping bio et champêtre au moulin de Belle-Née', '', 'Roméo Palierne, propriétaire du camping à la ferme du moulin de Belle-Née, à Sainte-Anne-sur-Vilaine, certifie l’atmosphère bucolique des lieux.  Dans une ambiance simple et champêtre, les campeurs peuvent désormais poser leur tente ou leur caravane un ou plusieurs jours au milieu des arbres. Ils rencontreront au détour d’un chemin des poules, un âne, des moutons, et pourront peut-être même approcher les abeilles qui butinent un peu plus loin. \r\n\r\nUn confort champêtre\r\nInstallé au moulin de Belle-Née depuis quelques années, Roméo Palierne propose de début mai à fin septembre la cueillette de fraises bio, en sept variétés, sur 9 000 plants (11 000 prévus en 2021).  Le camping répond à une envie de moment calme en nature, seul ou en famille, à un besoin d’hébergement proche de la Vilaine.  En effet, le camping borde la voie verte.\r\n\r\nSur place douche chaude, toilettes sèches et lavabos, barnum avec grande table, gazinière et frigo, et une capacité de six emplacements 20 personnes.  Ce moulin construit en 1830 est un lieu de partage et d’accueil de par sa nature. Je suis pleinement dans cette démarche depuis longtemps. \r\n\r\nRécoltes et cueillettes de produits bio\r\nRoméo souhaite faire prendre conscience que  l’homme fait partie intégrante de la nature, et ne vit pas seulement à côté ou au milieu d’elle.  Des démarches pour obtenir le label Accueil paysan sont d’ailleurs en cours.\r\n\r\nAprès la mise en place en 2019 d’une vingtaine de ruches en contrebas de ses trois hectares, qui lui permettent de vendre son miel, Roméo Palierne propose cette année pommes de terre et haricots verts, mûres et framboises à cueillir. C’est un essai concluant que je vais pérenniser. Tout est bio sauf le miel, dont les conditions d’obtention sont très compliquées, notamment le périmètre concerné autour des ruches.  Des productions livrées en magasins bio.', 'sainte-anne-sur-vilaine.camping-bio-et-champêtre-au-moulin-de-belle-nee.jpeg', '2020-08-04 00:00:00'),
(2, 'Agriculture. La méthanisation agricole à la française inquiète.', '', 'Pour éviter que les incidents ne se multiplient au gré du développement de ces unités de production d’énergie décarbonée, qui réduisent les émissions de gaz à effet de serre de la France, André Sergent, président de la chambre régionale d’agriculture de Bretagne appelle à la vigilance.  Il faut, dit-il, installer des systèmes de sécurité : une lagune pour recevoir les eaux de pluie ou d’éventuelles fuites de digestat, et un talus haut en bordure du point d’eau le plus proche pour réduire le risque de pollution.  En tant que représentant des professionnels, l’Association des agriculteurs méthaniseurs de France met actuellement en place une charte des bonnes pratiques certifiées par un organisme extérieur. Les Sergent sont directement concernés par la sécurité des installations.', 'agriculture-la-methanisation-agricole-a-la-francaise-inquiete.jpeg', '2020-08-27 00:00:00'),
(3, 'Alimentation. Après la viande, place aux faux poissons.', '', 'Nestlé passe ainsi à l’offensive sur une tendance de fond internationale. Après l’essor des jus végétaux puis de la « fausse viande », les substituts aux produits de la mer se développent. Les industries agroalimentaires emboîtent le pas aux start-up. La consommation, elle, est encore émergente : moins de 1 %. « Mais c’est une niche en croissance, portée par l’essor des régimes vegan, végétariens et surtout flexitariens (personnes réduisant leur consommation de protéines animales) », constate Céline Laisney, directrice du cabinet AlimAvenir et responsable du Club vigie alimentation.\r\n\r\nLa spécialiste des tendances alimentaires relève plusieurs initiatives. L’empereur américain de la viande Tyson a investi dans la start-up New Wave Foods, qui a mis au point une alternative aux crevettes à base de soja et d’algues. D’autres investissements soutiennent des start-up de l’agriculture cellulaire (cellules cultivées in vitro). En France, la société bordelaise Odontella a mis au point une alternative au saumon à base d’algues, distribuée en magasins véganes et bio.\r\n\r\nDe manière globale, si l’ultrafrais progresse bien en France, avec les yaourts et desserts végétaux, le marché des alternatives aux protéines animales n’y est pas aussi dynamique qu’aux États-Unis, au Royaume-Uni ou en Allemagne. « La France reste attachée aux produits animaux de par leur importance dans notre gastronomie, pointe Céline Laisney, mais le végétal peut prendre de l’ampleur. La restauration rapide et collective s’y intéresse, notamment avec les cantines qui doivent proposer un repas végétarien par semaine ».', 'alimentation.apres-la-viande-place-aux-faux-poissons.jpeg', '2020-08-27 00:00:00'),
(4, 'Autarcie ou exportation : quelle agriculture voulons-nous en Bretagne ?', '', 'Le climat comptera toujours : on ne produit de vin ni à l’équateur ni aux pôles et si l’olivier pousse en Bretagne, on n’en tire pas d’huile. Ces produits feront des kilomètres avant d’arriver sur nos tables. Il faut donc garder mesure et rester les pieds sur terre.\r\n\r\nIl n’empêche : le débat ouvert sur la production locale et les circuits courts est une interpellation essentielle pour la Bretagne.\r\n\r\nLa question doit être posée en termes simples : l’agriculture doit-elle avoir pour seul but l’alimentation des seuls habitants de la région ou doit-elle continuer à fournir la matière d’une importante industrie agroalimentaire exportatrice vers d’autres régions de France, d’autres pays d’Europe et du monde ?\r\n\r\nCette industrie est née dans les années 1960 à partir de l’énergie d’entrepreneurs souvent partant de peu : bouchers, charcutiers, boulangers, pâtissiers… Elle compte aujourd’hui pour 40 % de la production industrielle régionale, emplois des milliers d’ouvriers, employés, techniciens, ingénieurs. On ne tire pas un trait facilement sur cette réalité.\r\n\r\nLa Bretagne doit-elle être un territoire d’autarcie alimentaire ou un territoire d’exportation, conquérant et innovant ?\r\n\r\nVoilà un choix que la crise du Covid-19 oblige à clarifier pour fixer le cap des futures années et donner à ce secteur d’activité un horizon de confiance.\r\n\r\nLes partisans du choix de l’autarcie auront à présenter aux Bretons ses conséquences économiques et sociales. Les partisans du choix d’une Bretagne exportatrice auront à défendre l’agriculture raisonnée, moins intensive et moins utilisatrice de produits chimiques. Ils auront aussi à veiller au bien être animal et, par le dialogue social, à une qualité de travail dans les usines de transformation. Tout cela est déjà en cours mais c’est un mouvement lent. En matière économique, il y a plus d’évolutions que de révolutions.\r\n\r\nToute crise met au grand jour les alternatives qui s’offrent à nous et rien ne doit être omis.\r\n\r\nJe ne veux pas taire ma préférence : mieux vaut une Bretagne exportatrice qu’une Bretagne autarcique.', 'autarcie-ou-exportation-quelle-agriculture-voulons-nous-en-bretagne.jpeg', '2020-08-27 00:00:00');

-- --------------------------------------------------------

--
-- Structure de la table `produits`
--

CREATE TABLE `produits` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `title_href` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `story` text NOT NULL,
  `saison` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `stock` int(11) NOT NULL,
  `img` varchar(255) NOT NULL,
  `date_appro` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `produits`
--

INSERT INTO `produits` (`id`, `title`, `title_href`, `content`, `story`, `saison`, `type`, `stock`, `img`, `date_appro`) VALUES
(1, 'Tomates', 'Tomates', 'La tomate colore les étals de nos marchés et nos assiettes tout au long de l’année. Très simple à consommer, elle se prête à une infinité de préparations. Très riche au niveau nutritionnel, elle a de véritables atouts bien-être. Toutes ses qualités en font le légume le plus consommé en France.', 'La tomate est arrivée en France au XVIe siècle après sa découverte en Amérique du Sud. Elle était utilisée, à l’origine, comme plante d’ornement dans les jardins.\r\nOn trouve des milliers de variétés de tomates dans le monde. Elles se distinguent par leur forme, leur couleur, leur texture et leur goût. Les plus consommées en France sont les tomates rondes, les tomates cerises et les allongées.\r\nLa tomate, peu calorique, apporte de nombreux nutriments : vitamines (C et E notamment) et minéraux (magnésium et potassium).\r\nEn cuisine, elle se prépare très facilement et entre dans un grand nombre de préparations aussi bien crue que cuite. Elle se décline même jusqu’au dessert !\r\nSi elle se consomme comme un légume (donc communément considérée comme telle), la tomate est botaniquement un fruit.\r\nLa tomate est disponible toute l’année.', 'Janvier, Février, Mars, Avril, Août, Septembre, Octobre, Novembre, Décembre', 'legume', 100, 'tomate.jpg', '2020-08-04 00:00:00'),
(2, 'Pomme', 'Pomme', 'Cultivée dès le Néolithique, la pomme est aujourd\'hui le fruit le plus consommé par les Français. Ses techniques de production se sont perfectionnées au cours des siècles, offrant un large éventail de variétés et de saveurs. La pomme rythme tous les moments de la journée, croquée au naturel ou cuisinée pour des mets sucrés ou salés. Aliment plaisir, ses qualités nutritionnelles en font également un allié incontournable de votre bien-être.', 'Une pomme pèse 150 grammes en moyenne. Selon les variétés, sa peau est verte, rouge, bicolore ou tachetée : une véritable farandole de couleurs ! Sa chair est croquante ou farineuse, douce ou acidulée.\r\nParmi les milliers de variétés de pommes existantes, près de cent sont produites en France, dont une trentaine en très grande quantité.\r\nRâpée ou entière, crue ou cuite, poêlée ou au four, la pomme se prête aux cuisines les plus simples comme les plus sophistiquées. Alors laissez-la vous surprendre !\r\nD’un faible apport calorique, la pomme renferme antioxydants et fibres. Fruit adapté à l’alimentation des sportifs, elle participe à l’équilibre digestif et constitue une mine de vitamines et de nutriments bénéfiques.\r\nLa pomme est disponible tout au long de l’année.', 'Janvier, Février, Mars, Avril, Mai, Septembre, Octobre, Novembre, Décembre', 'fruit', 345, 'pomme.jpg', '2020-08-18 00:00:00'),
(3, 'Melon', 'Melon', 'En été, le melon garnit généreusement les étals et parfume agréablement nos paniers. Rond et savoureux, il fait partie des fruits et légumes d\'été préférés des Français. Il se consomme aujourd’hui surtout comme un fruit, mais agrémente également des préparations salées.', 'Parmi les différents types commerciaux existants, le melon de type charentais est le plus produit et consommé en France.\r\n• En dépit de son parfum sucré, le melon n’est pas un fruit. Appartenant à la famille des cucurbitacées, comme la courgette ou le potiron, il s’agit d’un légume. Et, avec une saison concentrée sur quelques mois seulement, c’est même le troisième légume le plus consommé des Français !\r\n• Sa chair savoureuse et parfumée se déguste aussi bien nature que cuisinée. Il égaye très simplement une fin de repas ou se mêle à une entrée fraîche et légère.\r\n• Regorgeant de vitamines et de minéraux, le melon présente de nombreux atouts forme. Très riche en eau et peu calorique, il vient à point pour nous désaltérer lors des mois les plus chauds de l’année !', 'Juin, Juillet, Août, Septembre', 'legume', 43, 'melon.jpg', '2020-08-18 00:00:00'),
(4, 'Prune', 'Prune', 'Juteuse et désaltérante, la prune est l’alliée fraîcheur de l’été ! Relativement peu calorique, elle peut se consommer sans problème à tout moment de la journée. Les plus gourmands peuvent même la cuisiner : quoi de meilleur qu’une tarte aux prunes ou un clafoutis ? N’hésitez pas : vous ferez le plein de vitamines et de minéraux et votre digestion s’en portera mieux. ', 'Une prune pèse 30 grammes en moyenne. Selon les variétés, sa peau est rouge, bleue, jaune, verte… Sa chair est sucrée ou acidulée.\r\nLa prune se croque directement en bouche ou se cuisine en tartes, en flan, en confitures, etc. On le sait moins, mais elle se prête également aux préparations salées.\r\nTrès sucrée et juteuse, la prune est cependant assez peu calorique et très désaltérante. Vous pouvez donc y succomber à toute heure de la journée. Généreuse en vitamines, en minéraux et en fibres, la prune est au service de votre forme et de votre digestion.\r\nLa pleine saison de la prune reste courte : quatre mois seulement, incluant octobre.', 'Juillet, Août, Septembre, Octobre', 'fruit', 235, 'prune.jpg', '2020-08-18 00:00:00'),
(5, 'Fraises', 'Fraises', 'Chaque année au printemps, les fraises font leur retour sur les étals, et ce pour notre plus grand plaisir ! Elles redonnent des couleurs à nos assiettes, émoustillent nos papilles… et surtout nous apportent une bonne dose de vitamines et d’antioxydants. Peu caloriques, elles peuvent même se consommer sans modération. Il ne vous reste plus qu’à trouver la variété la plus à votre goût…', 'Une fraise pèse 10 grammes en moyenne. Selon les variétés, sa robe peut être rouge ou orangée et sa chair sucrée ou acidulée.\r\nPrincipalement consommée crue, la fraise peut également se prêter à des cuissons rapides à la poêle ou au four en papillote. Elle se cuisine volontiers, que ce soit en version sucrée ou en version salée. Tentez l’expérience, vous ne serez pas déçus !\r\nLa fraise est l’un des fruits qui contient le plus de vitamine C. À l’approche des beaux jours, elle prend ainsi le relais des agrumes pour recharger vos batteries. Comme tous les fruits rouges, elle est, par ailleurs, dotée d’un excellent pouvoir antioxydant. Peu calorique, vous pouvez en manger sans compter.\r\nLe cœur de saison de la fraise se situe entre fin mars et juin ; certaines variétés continuent à approvisionner le marché tout l’été puis les remontantes prennent le relais jusqu’en novembre.', 'Avril, Mai, Juin', 'fruit', 800, 'fraises.jpg', '2020-08-18 00:00:00'),
(6, 'Carotte', 'Carotte', 'Toujours disponible et très bon marché, la carotte est aujourd’hui le deuxième légume le plus consommé en France, juste derrière la tomate. Elle renferme de très nombreux minéraux et vitamines. D’après l’adage, elle rendrait même aimable…', 'Une carotte pèse 125 grammes en moyenne. Longtemps restée blanche et fibreuse, elle est aujourd’hui d’un beau rouge orangé et très savoureuse.\r\nEn cuisine, la carotte se décline sur toute la palette des textures et des saveurs. Cuite en gratin ou en purée, crue râpée ou taillée en bâtonnets, épicée, sucrée, glacée… avec elle, tout est possible !\r\nLa carotte est un vrai légume allié du bien-être, tant pour les enfants et que pour les adultes : une seule portion de 100 grammes couvre jusqu’à 200 % de nos besoins quotidiens en bêtacarotène ! Sans parler de ses nombreux minéraux.\r\nLa carotte est disponible toute l’année.', 'Janvier, Février, Mars, Août, Septembre, Octobre, Novembre, Décembre', 'legume', 147, 'carotte.jpg', '2020-08-23 00:00:00'),
(7, 'Framboise', 'Framboise', 'Sensuelle et charnue, la framboise possède une saveur parfumée et suave. Elle se déguste nature ou cuisinée, mais reste fragile. Ce petit fruit rouge présente un apport calorique modéré : avec elle, alliez plaisir en bouche et bien-être !', 'Sur les étals, vous rencontrerez plusieurs variétés de framboises. Habituellement rouges, certaines peuvent être jaunes, orange, ambrées, noires - à ne pas confondre avec la mûre - ou blanches. La chair du fruit est sucrée, suave et acidulée.\r\n\r\nEn France, la framboise pousse encore à l\'état sauvage dans certaines régions. La culture de ce fruit s\'est développée dans les années 1950 durant lesquelles de nouvelles variétés – remontantes (permettant plusieurs récoltes annuelles) et plus robustes - ont été sélectionnées.\r\n\r\nCroquée nature au retour des courses ou utilisée dans une recette sophistiquée, la framboise a tous les atouts pour vous séduire !\r\nSon faible apport calorique en fait un fruit idéal pour les gourmands qui surveillent leur ligne. Elle contient par ailleurs des antioxydants, des fibres et des minéraux.\r\n\r\nLa framboise est disponible d\'avril à novembre.', 'Juillet, Août, Septembre', 'fruit', 75, 'framboise.jpg', '2020-08-23 00:00:00'),
(8, 'Poireau', 'Poireau', 'Le poireau se retrouve toute l’année sur les étals des marchés. Légume résistant, il entre dans la composition de nombreux plats grâce à son parfum si particulier et à sa saveur aillée. Originaire du Moyen-Orient, il a traversé les siècles pour être aujourd’hui le neuvième légume le plus consommé par les Français.', 'Le poireau est l’un des légumes phare de l’hiver. Il est produit dans de nombreuses régions françaises et se décline en plusieurs variétés.\r\nIl serait né au Moyen-Orient. Légume populaire chez les Égyptiens et les Romains, il ne cesse, au fil des siècles, de faire de nouveaux adeptes.\r\nPeu calorique, le poireau présente de sérieux atouts nutritionnels par sa richesse en fibres, vitamines et minéraux.\r\nCe légume se cuisine généralement cuit, à la vapeur, braisé ou préalablement blanchi à l’eau avant d’être accommodé de diverses manières.\r\nLe poireau appartient à la famille des alliacées, comme l’ailet l’oignon. Il s’agit d’un légume à bulbe. Sa partie enterrée est blanche. Son corps, appelé « fût » est constitué de feuilles qui s’emboîtent.\r\nLe poireau est disponible tout au long de l’année. Cependant, son cœur de saison se situe entre septembre et avril.\r\nLa période primeur a lieu de fin avril-début mai à fin juillet.', 'Janvier, Février, Mars, Avril, Septembre, Octobre, Novembre, Décembre', 'legume', 230, 'poireau.jpg', '2020-08-23 00:00:00'),
(9, 'Poivron', 'Poivron', 'Symbole d’été, de vacances et de grillades, le poivron arbore ses couleurs joyeuses sur les marchés. Légume-fruit comme la tomate, il s’intègre facilement dans toutes les recettes gorgées de soleil… Peu calorique, il est également apprécié pour ses vitamines.', 'Variété de piment doux, le poivron produit de gros fruits, frais et colorés.\r\nLa palette des couleurs va du vert vif au brun foncé, en passant par le jaune d’or ou le vermillon.\r\nLe panel des saveurs s’étend de l’amer-poivré au sucré.\r\nLa récolte s’étale de fin mai à début novembre.', 'Juin, Juillet, Août, Septembre', 'legume', 450, 'poivron.jpg', '2020-08-23 00:00:00'),
(10, 'Poire', 'Poire', 'Arrivée en France au XVIe siècle, la poire s’est rapidement imposée dans tout le pays. Disponible toute l’année, elle se décline en une dizaine de variétés qui se répartissent entre l’été et la saison d’automne-hiver. Peu calorique, elle renferme de nombreux nutriments et des fibres. Dégustez-la à la croque ou dévoilez toute sa douceur dans de nombreux desserts ou dans des recettes salées. Adoptez-la, elle ne vous veut que du bien !', 'Une poire pèse 120 grammes en moyenne. Sa peau lisse se décline en teintes allant du vert au jaune. Sa chair fondante et sucrée en fait le cinquième fruit le plus consommé en France.\r\nD’un faible apport calorique, la poire est gorgée de sucres lents, de vitamines et de fibres. En été comme en hiver, profitez de ses bienfaits et appréciez ses différentes variétés !\r\nSavoureuse nature, elle se prête également à de nombreux accompagnements ou préparations aussi bien sucrées que salées.\r\nS’il existe près de 2 000 variétés, la production de poires en France se concentre sur une dizaine d’entre elles, distinguées en poires d’automne-hiver et en poires d’été.\r\nLeur culture est essentiellement localisée dans le sud et dans le centre du pays.', 'Janvier, Février, Mars, Avril, Mai, Juin, Juillet, Août, Septembre, Octobre, Novembre, Décembre', 'fruit', 340, 'poire.jpg', '2020-08-23 00:00:00'),
(11, 'Céleri-branche', 'Céleri-branche', 'Plante médicinale et aphrodisiaque avant d’entrer en cuisine, le céleri-branche nous régale aujourd’hui de la fin du printemps jusqu\'au milieu de l\'hiver. Sa saveur marquée et sa texture croquante le rendent tout aussi délicieux cru que cuit. Par petites touches ou en ingrédient vedette, le céleri-branche se prépare et s’accommode avec facilité, tout en vous permettant de faire le plein de vitalité. Alors, prêt ? Croquez !', 'Une tige de céleri-branche pèse 30 grammes en moyenne. Contrairement au céleri-rave, il est cultivé pour ses côtes très blanches et aromatiques, croquantes en bouche.\r\nPauvre en calories, mais riche en vitamines ! Le céleri-branche est un concentré de nutriments essentiels, notamment calcium et vitamine C, nutriments indispensables pour votre tonus au quotidien.\r\nÀ la croque ou cuit, le céleri-branche parfume agréablement tous vos plats. Pensez à lui réserver plus de place dans vos recettes au quotidien, vous serez surpris de son ampleur aromatique.\r\nDe différentes provenances en France (Bretagne, Languedoc-Roussillon et Provence) le céleri-blanche est en \"cœur de saison\" de la fin du printemps jusqu\'au milieu de l\'hiver (pour les approvisionnements du sud de la France). Il est cependant disponible sur nos étals toute l\'année.', 'Juillet, Août, Septembre, Octobre, Novembre, Décembre', 'legume', 220, 'celeri-branche.jpg', '2020-08-23 00:00:00'),
(12, 'Laitue', 'Laitue', 'Qui ne connait pas la laitue ? Cinquième légume le plus consommé des français, elle est aussi l’un des plus populaires dans le monde. La Lactuca sativa regroupe plusieurs centaines de variétés ; guère étonnant puisqu’elle est cultivée depuis la plus lointaine Antiquité. Croquante ou fondante, charnue ou légère, elle se déguste surtout en salade, mais se prête à bon nombre de préparations cuites.             ', 'Plante annuelle, ses nombreuses variétés permettent d’en consommer de janvier à décembre.\r\nAvec la mâcheet la chicorée, la laitue constitue la troisième grande famille de salade.\r\nPeu calorique, elle vous apporte une grande variété de minéraux et d’oligo-éléments. Également riche en fibres, sa teneur en vitamine C n’est pas négligeable.\r\nEn France, la laitue est le quatrième légume le plus produit, derrière la tomate, la carotteet le chou-fleur. Sa culture se répartit sur l’ensemble du territoire.', 'Mai, Juin, Juillet, Août, Septembre', 'legume', 500, 'laitue.jpg', '2020-08-23 00:00:00'),
(13, 'Pomme de terre', 'Pomme-de-terre', 'Consommée depuis le XIXe siècle, la pomme de terre est rapidement devenue le légume préféré des Français. Des centaines de variétés sont présentes sur les étals, chacune réservée à un usage spécifique. La pomme de terre se prête à tous types de cuissons et de recettes, qui facilitent son intégration dans votre alimentation quotidienne. Et ne vous en privez surtout pas : c’est un véritable concentré d’énergie et de vitamines !', 'Une pomme de terre pèse entre 80 et 320 grammes selon le calibrage. La couleur de la peau et de la chair varie du jaune pâle au violet en passant par le rose. Plus ou moins grosse, la pomme de terre possède une pulpe aux textures différentes selon les variétés.\r\nD’un apport calorique modéré, la pomme de terre est très riche en glucides. Elle apporte également des vitamines et des nutriments. C’est une véritable source d’énergie en hiver.\r\nLa pomme de terre se consomme exclusivement cuite. Elle se prête à de nombreuses préparations gourmandes, poêlées, vapeur, en purée, au four ou en potage.\r\nLa France compte plus de 150 espèces classifiées selon la texture de leur chair et leur usage culinaire', 'Janvier, Février, Mars, Septembre, Octobre, Novembre, Décembre', 'legume', 750, 'pomme-de-terre.jpg', '2020-08-23 00:00:00'),
(14, 'Champignons', 'Champignons', 'On a beau les classer parmi les légumes, les champignons cultivés ne sont ni des animaux, ni des végétaux. Ils appartiennent au groupe des « fungi », et plus exactement à la catégorie des saprophytes.\r\n\r\nIls sont à distinguer des champignons sauvages, dont la présence, sujette aux aléas de la météo, est irrégulière et le plus souvent très courte.', 'Les champignons cultivés apportent leurs arômes subtils et leur saveur douce à la cuisine de tous les jours comme aux plats plus festifs. Faibles en calories, riches en oligo-éléments, ils se consomment comme des légumes à part entière, crus ou cuits, en salade, sautés, dans des poêlées de légumes, en purée, en tartes salées, etc.\r\n\r\nLe plus populaire d’entre tous les champignons cultivés est sans aucun doute le champignon de Paris. Mais il est loin d’être le seul sur nos étals. D’autres variétés sont de plus en plus appréciées, parmi lesquelles le pied-bleu, le pleurote et le shiitake.\r\n\r\nContrairement aux champignons sauvages, ces variétés sont disponibles toute l’année.', 'Janvier, Février, Mars, Avril, Mai, Juin, Septembre, Octobre, Novembre, Décembre', 'legume', 100, 'champignons.jpg', '2020-08-23 00:00:00'),
(15, 'Mâche', 'Mâche', 'Avec la laitue et la chicorée, la mâche constitue la troisième grande famille de salades. Ces rosettes de feuilles rondes, d’un beau vert foncé et brillant, sont charnues et croquantes. Originaire du bassin méditerranéen, la mâche fait figure de salade hivernale de référence sur les étals, même si elle se consomme tout au long de l’année. Son goût subtil et raffiné vous régale lorsqu’elle est crue, en salade, mais aussi cuite, en velouté et en accompagnement. ', 'La France est le premier producteur européen de mâche.\r\nCette petite salade regorge d’atouts nutritionnels. Riche en vitamines (elle contient trois fois plus de vitamines C que la laitue) et en bêta-carotène, elle présente aussi une forte teneur en fibres et, plus rare pour un légume, en Oméga 3.\r\nDeux variétés sont cultivées en France : la mâche à petite graine, dite mâche verte, et plus confidentielle, la mâche à grosse graine, ou mâche blonde.\r\nLa culture de ce produit du terroir, connu et apprécié depuis l’Antiquité, réclame une grande technicité et un vrai savoir-faire.\r\nLa mâche est disponible toute l’année.', 'Janvier, Février, Mars, Avril, Octobre, Novembre, Décembre', 'legume', 190, 'mache.jpg', '2020-08-23 00:00:00'),
(16, 'Asperge', 'Asperge', 'Blanche, violette ou verte, l’asperge est un délice de printemps à ne pas manquer ! Elle se déguste simplement avec un panaché de vinaigrettes ou se cuisine en gratin, en velouté, etc. Longtemps considérée comme un produit de luxe, elle est aujourd’hui beaucoup plus abordable.', 'Une asperge pèse entre 20 et 80 grammes. Elle peut être blanche, violette ou verte, selon sa durée d’exposition au soleil. Son goût amer peut être plus ou moins prononcé.\r\nAvant de la consommer, vous devrez faire preuve d’un peu de patience et la cuire à la vapeur ou à l’eau. Vous pourrez ensuite la servir en entrée ou en garniture. Elle se marie, en effet, très bien avec les viandes.\r\nL’asperge est riche en potassium, en magnésium et en vitamines. Relativement peu calorique, vous pouvez la manger sans crainte.\r\nSi l\'on peut trouver des asperges fraîches sur les étals pendant les fêtes de fin d\'année ou à l\'orée des beaux jours, il s\'agit bel et bien d\'un légume de printemps.', 'Avril, Mai, Juin', 'legume', 90, 'asperge.jpg', '2020-08-23 00:00:00'),
(17, 'Céleri-rave', 'Céleri-rave', 'Connu depuis l’Antiquité, cultivé dès le 16e siècle, le céleri-rave a fait progressivement son entrée dans les cuisines. Ce légume rustique s’est développé et a imposé sa présence sur les étals grâce à sa chair savoureuse, croquante quand elle est crue, fondante après cuisson. Ce beau céleri tout en rondeur est très concentré en vitamines et minéraux essentiels, tout en étant très peu énergétique. Invitez-le régulièrement dans vos assiettes pour savourer tous les bienfaits de sa chair délicate.', 'Un céleri-rave pèse 1 kg en moyenne. Sa peau uniformément pâle recouvre une chair blanchâtre, croquante quand elle est consommée crue.\r\nPauvre en calories, le céleri-rave est un légume riche en vitamines, nutriments et oligoéléments. Pensez à le croquer ou à le cuisiner régulièrement pour intégrer tous ses bienfaits à vos menus.\r\nDélicieux râpé, croquant à souhait, le céleri-rave est également un régal poêlé, frit ou accommodé en soupe, gratin ou purée.', 'Janvier, Février, Mars, Octobre, Novembre, Décembre', 'legume', 315, 'celeri-rave.jpg', '2020-08-23 00:00:00'),
(18, 'Potiron', 'Potiron', 'Symbole d’automne, le potiron est originaire d’Amérique du Sud. Très présent dans les jardins d’antan, il redevient populaire depuis plusieurs années. Ses couleurs, sa forme et ses saveurs se marient à merveille avec tous les plats, traditionnels ou audacieux. Les enfants l’adorent.', 'Le potiron est une cucurbitacée à la saveur douce.\r\nIl présente de multiples apparences, avec ses différentes variétés, ses différentes tailles et ses différentes formes.\r\nIl se prépare aussi bien en entrée, qu’en plat principal, et même en dessert.\r\nNe le confondez pas avec la citrouille, plus ronde, plus orange vif, mais surtout bien moins savoureuse : c’est d’ailleurs elle plutôt que le potiron qu’on évide pour Halloween !\r\nIntéressant pour son apport en vitamine A et ses fibres douces, il est peu calorique tout en restant très nourrissant.\r\nLe potiron est disponible toute l’année.', 'Janvier, Octobre, Novembre, Décembre', 'legume', 305, 'potiron.jpg', '2020-08-23 00:00:00'),
(19, 'Abricot', 'Abricot', 'Apparu il y a 5 000 ans, l’abricot est aujourd’hui un fruit apprécié de tous en été. Les variétés se sont développées au fil des années, multipliant les textures et les saveurs. Cultivé dans le sud-est de la France, l’abricot apparaît aux beaux jours et garnit les étals de sa chair gorgée de soleil. Riche en nutriments essentiels, il se décline dans des recettes aussi bien sucrées que salées.', 'Un abricot pèse 45 grammes en moyenne. Plus ou moins gros selon les variétés, il conserve une teinte orangée caractéristique, souvent tachetée de rouge, et une peau duveteuse. Sa chair est pulpeuse, sucrée et juteuse.\r\nD’un apport calorique moyen, l’abricot est un des fruits les plus riches en provitamine A (ou carotène) : un fruit apporte pratiquement 50% du besoin quotidien. Croquez l’abricot à pleines dents pour profiter de cette source d’énergie gourmande.\r\nS’il est délicieux nature, l’abricot s’accommode aussi simplement en dessert, relevé de citron et/ou d’épices. Plus audacieux, il accompagne également les mets salés (canard, porc, viandes et poissons fumés, mâche, épinards).\r\nIl existe de multiples variétés d’abricots cultivées en France. Les terroirs favorables à l’espèce leur confèrent une grande saveur.\r\nL’abricot est un fruit estival dont les variétés se succèdent au fil de la saison.', 'Juin, Juillet, Août', 'fruit', 230, 'abricot.jpg', '2020-08-23 00:00:00'),
(20, 'Nectarine', 'Nectarine', 'La pêche-nectarine est le 7e fruit le plus consommé en France. Originaire d’Asie, elle est présente sur nos étals depuis le XVe siècle. Sucrée et très désaltérante, elle fait le régal des gourmands à la belle saison. Elle se consomme nature mais se marie également à de savoureux plats et desserts.', 'Une pêche-nectarine pèse 150 grammes en moyenne. Sa peau lisse ou duvetée prend différentes couleurs déclinant les nuances du blanc au jaune, en passant par l’orange ou le rose. Sa chair parfumée est jaune, blanche, ou même rouge.\r\nD’un apport calorique moyen, la pêche renferme de nombreuses vitamines et des antioxydants.\r\nElle s’associe avec bonheur à des mets salés ou sucrés, ou se mange nature. Juteuse et rafraîchissante, la pêche est un fruit estival par excellence !', 'Juin, Juillet, Août', 'fruit', 260, 'peche.jpg', '2020-08-23 00:00:00'),
(21, 'Citron', 'Citron', 'Le citron occupe une place de choix dans nos cuisines. On l\'aime pour sa chair juteuse, sa saveur qui oscille entre acide et amère, et sa belle couleur jaune doré. Fruit tonique, riche en vitamine C, le citron est aussi source de bienfaits pour votre organisme. Plein de caractère, le citron vert est un fruit tropical. Festif et convivial, il possède un arôme caractéristique qui dynamise vos plats et cocktails. En prime, ce fruit regorge d\'atouts pour votre bien-être.', 'Un citron pèse 120 g en moyenne. Selon les variétés, sa peau revêt plusieurs nuances, du jaune vif au jaune doré. Sa chair juteuse offre un large panel de saveurs, allant du sucré à l’amer, en passant par l’acide.\r\nEn France, trois ou quatre variétés de citrons sont principalement commercialisées. Une partie provient de Côte-d\'Azur et de Corse.\r\nEn assaisonnement ou en quartiers dans une salade, en jus rafraîchissant ou en limonade : il y a mille et une façons de se régaler du citron.\r\nRiche en vitamine C, son apport calorique est pratiquement négligeable. Sa concentration en nutriments est une bonne raison supplémentaire de le déguster au quotidien !\r\nLe citron est disponible tout au long de l\'année.\r\nUn citron vert pèse en moyenne 100 g. Plus petit et plus trapu que le citron jaune, son écorce se colore à maturité d\'un joli vert brillant. Tendre, acide et très juteuse, sa pulpe possède un arôme caractéristique. Sa peau est lisse, mince, parfois coriace et adhérente.\r\nLe citron vert est très utile en cuisine. Recherché pour son jus et sa pulpe, il apporte fraîcheur et exotisme.\r\nLe citron vert est disponible tout au long de l\'année.', 'Février, Mars, Avril, Mai, Juin, Juillet, Août, Septembre, Novembre, Décembre', 'fruit', 630, 'citron.jpg', '2020-08-23 00:00:00');

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `role` varchar(255) NOT NULL DEFAULT 'user',
  `name` varchar(255) NOT NULL,
  `firstname` varchar(255) NOT NULL,
  `mail` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `fav` text,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `role`, `name`, `firstname`, `mail`, `password`, `fav`, `created_at`) VALUES
(33, 'admin', 'Admin_3WA', 'Admin', 'admin@3wa.fr', '$2y$10$BTmmQLbP/90CXer1fCaDqe3q3wxjN/s807.ZVb8cjzzxlvlMv1MOK', NULL, '2020-11-26 11:14:20');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `produits`
--
ALTER TABLE `produits`
  ADD PRIMARY KEY (`id`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT pour la table `produits`
--
ALTER TABLE `produits`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=22;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=34;
