<h1>ADMINISTRATION</h1>
<div class="alert_error">
    <p>ATTENTION ! N'oubliez pas de cliquer sur déconnexion en haut à droite pour vous déconnecter de l'espace administration
        ou cliquez <a href="index.php?ctrl=user&task=logOut" title="Déconnexion">ICI</a>.
    </p>
</div>

<?php if (isset($_SESSION['message'])) : ?>
    <?php if (isset($_SESSION['messageType']) and $_SESSION['messageType'] === 'error') : ?>
        <div class="alert_error">
            <p><?= $_SESSION['message'] ?></p>
        </div>
    <?php else : ?>
        <div class="alert_success">
            <p><?= $_SESSION['message'] ?></p>
        </div>
    <?php endif; ?>

    <?php unset($_SESSION['messageType']);
    unset($_SESSION['message']); ?>
<?php endif; ?>


<ul class="add_buttons">
    <li class="adm_li add_button"><a href="index.php?ctrl=user&task=render&page=newProduit" class="btn adm_btn" title="Ajouter un produit">Ajouter un produit</a></li>
    <li class="adm_li add_button"><a href="index.php?ctrl=user&task=render&page=newArticle" class="btn adm_btn" title="Ajouter un article">Ajouter un article</a></li>
    <li class="adm_li add_button"><a href="index.php?ctrl=user&task=render&page=newUser" class="btn adm_btn" title="Ajouter un utilisateur">Ajouter un utilisateur</a></li>
</ul>

<h2>Tous les articles :</h2>

<table>
    <thead>
        <tr>
            <th>Titre</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($allArticles as $article) : ?>
            <tr class="table_line">
                <td><?= $article['title'] ?></td>
                <td><a href="index.php?ctrl=articles&task=read&page=article&id=<?= $article['id'] ?>" class="btn btn_upd_del" title=" Modifier">Modifier</a></td>
                <td><a href="index.php?ctrl=articles&task=delete&page=adminSpace&id=<?= $article['id'] ?>" class="btn btn_upd_del" title="Supprimer">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>


    </tbody>



</table>


<h2>Tous les produits :</h2>

<table>
    <thead>
        <tr class="adm_products">
            <th>Titre</th>
            <th>Type</th>
            <th>Stock</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($allProducts as $produit) : ?>
            <tr class="table_line adm_products">
                <td><strong><?= $produit['title'] ?></strong></td>
                <td><?= $produit['type'] ?></td>
                <td><?= $produit['stock'] ?></td>
                <td><a href="index.php?ctrl=produits&task=read&page=produit&id=<?= $produit['id'] ?>" class="btn btn_upd_del" title="Modifier">Modifier</a></td>
                <td><a href="index.php?ctrl=produits&task=delete&page=adminSpace&id=<?= $produit['id'] ?>" class="btn btn_upd_del" title="Supprimer">Supprimer</a></td>
            </tr>

        <?php endforeach; ?>

    </tbody>


</table>



<h2>Tous les utilisateurs :</h2>

<table>
    <thead>
        <tr>
            <th>Nom</th>
            <th>Prénom</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($allUsers as $user) : ?>
            <tr class="table_line">
                <td><?= $user['name'] ?></td>
                <td><?= $user['firstname'] ?></td>
                <td><a href="index.php?ctrl=user&task=read&page=userSpace&id=<?= $user['id'] ?>" class="btn btn_upd_del" title="Modifier">Modifier</a></td>
                <td><a href="index.php?ctrl=user&task=delete&page=adminSpace&id=<?= $user['id'] ?>" class="btn btn_upd_del" title="Supprimer">Supprimer</a></td>
            </tr>
        <?php endforeach; ?>

    </tbody>


</table>