<!-- PARTIE ADMIN -->
<?php if (isset($_SESSION['status']) and $_SESSION['role'] === "admin") : ?>
    <form enctype="multipart/form-data" action="index.php?ctrl=articles&task=update&page=article&id=<?= $item['id'] ?>" method="post" id="update_article_form">
        <h1>Modification de l'article</h1>
        <div id="update_article">
            <fieldset>
                <input type="hidden" name="id" id="id" value="<?= $item['id'] ?>">
                <div id="update_title">
                    <label for="title">Titre :</label>
                    <input type="text" value="<?= $item['title'] ?>" name="title" id="title" class="Titre">
                </div>

                <div id="update_img">
                    <label for="img">Image :</label>
                    <div><img src="library/img/articles/<?= $item['img'] ?>" alt="<?= $item['title'] ?>"></div>
                    <input type="file" name="img" id="img" class="Image input_update_img" accept=".jpg,.jpeg,.png">
                </div>

                <div id="update_content">
                    <label for="content">Contenu :</label>
                    <textarea name="content" id="content" cols="30" rows="10"><?= $item['content'] ?></textarea>
                </div>
                <div class="forBtn center">
                    <button class="btn btn_form update_article_form">Mettre à jour</button>
                </div>
            </fieldset>
        </div>
    </form>
<?php else : ?>
    <!-- PARTIE USER -->
    <h1 id="article_title" class="center"><?= $item['title'] ?></h1>
    <small>Date de publication : <?= $item['created_at'] ?></small>
    <div id="article_img"><img src="library/img/articles/<?= $item['img'] ?>" alt="<?= $item['title'] ?>"></div>

    <p><?= $item['content'] ?></p>


<?php endif; ?>