<h3>Consultez tous nos articles concernant l'agriculture.</h3>

<ul id="articles_blog">

    <?php foreach ($items as $value) : ?>
        <li class="blog_li">
            <div class="blog_article_img center">
                <img src="library/img/articles/<?= $value['img'] ?>" alt="<?= $value['img'] ?>">
            </div>
            <div class="article_pres">
                <h4 class="h4_blog_title center"><a href="index.php?ctrl=articles&task=read&page=article&id=<?= $value['id'] ?>"><?= $value['title'] ?></a></h4>
                <small>Écrit le : <?= $value['created_at'] ?> </small>

            </div>

        </li>
    <?php endforeach; ?>
</ul>

