<h3>Des suggestions ? Une question ? Dites nous tout.</h3>

<?php if (isset($_SESSION['message'])) : ?>
    <?php if (isset($_SESSION['messageType']) and $_SESSION['messageType'] === 'error') : ?>
        <div class="alert_error">
            <p><?= $_SESSION['message'] ?></p>
        </div>
    <?php else : ?>
        <div class="alert_success">
            <p><?= $_SESSION['message'] ?></p>
        </div>
    <?php endif; ?>

    <?php unset($_SESSION['message']); ?>
<?php endif; ?>


<!-- FORMULAIRE DE CONTACT -->

<form id="contact_form" method="post" action="index.php?ctrl=user&task=mailContact&page=contact=pageTitle=Contact">
    <fieldset>
        <legend>Informations</legend>

        <div id="name_div" class="contact_form_div">
            <label for="contact_name">Nom</label>
            <input type="text" name="nom" id="contact_name" class="Nom" placeholder="Dupont">
        </div>

        <div id="firstname_div" class="contact_form_div">
            <label for="contact_firstname">Prénom</label>
            <input type="text" name="prenom" id="contact_firstname" class="Prénom" placeholder="André">
        </div>

        <div id="mail_div" class="contact_form_div">
            <label for="contact_mail">E-mail</label>
            <input type="email" name="mail" id="contact_mail" class="E-mail" placeholder="andre.dupont@gmail.com">
        </div>
    </fieldset>

    <fieldset>
        <legend>Message</legend>
        <div class="center_text_area center">
            <textarea name="message" id="contact_message" class="Message" cols="35" rows="10" placeholder="Tapez votre message"></textarea>
        </div>
    </fieldset>

    <div class="contact_btn center">
        <button type="submit" class="btn btn_form contact_form">Envoyer <span class="glyphicon glyphicon-envelope"></span></button>
    </div>

</form>