<article id="agri_story">
    <h2>Une brève histoire de l'agriculture biologique</h2>
    <p>
        En une soixantaine d’années, l’agriculture bio est progressivement passée d’une position marginale à une <strong>question centrale</strong> de société. C’est la démarche la plus aboutie pour la protection de l’environnement, de la biodiversité et du bien-être animal, ce qui lui confère un statut particulier et des bases solides pour l’avenir.
        L’agriculture biologique est née d’une multitude d’initiatives d’agronomes, de médecins, d’agriculteurs et de consommateurs qui, dans les années 1920, ont généré de nouveaux courants de pensées reposant sur des principes éthiques et écologiques, et initié un mode alternatif de production agricole.
    </p>
</article>

<article id="natural_product">
    <h2>Des produits naturels et authentiques</h2>
    <p>
        L’objectif pour les transformateurs de produits biologiques est d’avoir recours à des procédés de formulation et de transformation assurant le maintien des qualités nutritionnelles présentes dans les matières premières à tous les stades de fabrication. Ainsi, les méthodes biologiques, mécaniques et physiques sont privilégiées (ex : farine sur meule, huile de pression à froid…).
        <ul id="natural_product_ul">
            <li class="natural_product_li">Le transformateur de produits bio <strong>n’utilise pas de colorants et arômes chimiques de synthèse, ni d’exhausteurs de goût.</strong></li>
            <li class="natural_product_li"><strong>Le nombre d’additifs autorisés est fortement restreint</strong> (47 contre 300 en conventionnel) et la plupart sont d’origine agricole ou naturelle. Ne sont autorisés en bio que ceux dont l’usage est indispensable à la préparation ou à la conservation de certains aliments transformés.</li>
            <li class="natural_product_li"><strong>L’enrichissement en vitamines, minéraux, antioxydants… est interdit en bio</strong>, sauf si cela est exigé par la loi (ex : petits pots pourbébé).</li>
            <li class="natural_product_li">Les traitements ionisants sont interdits.</li>
        </ul>
    </p>
</article>

<article id="who_are_we">

    <h2>Qui sommes nous ?</h2>
    <p>Je me présente, je suis Patrick, agriculteur depuis plus de 30 ans dans l'Oise. Je suis le président d'une association d'agriculteur
        de l'Oise appelée Agri & Co, créee en 2005 pour répondre à la demande de clients qui veulent prendre soin de leur santé et de la nature. L'objectif
        est de vous proposer des fruits et légumes de saison, cultivés dans le respect de l'environnement et sans pesticides.</p>
    <p>Vous pourrez donc consulter ici la liste de tous nos produits et faire une liste de course pour ne rien oublié lors de votre visite.
        Nous sommes, chers amis, impatient de vous rencontrer.</p>

    <h2>Par où commencer ?</h2>
    <p>Inscrivez vous en cliquant <a href="index.php?ctrl=user&task=render&page=connexion&pageTitle=Connexion/Inscription">ici</a>, puis une fois inscrit vous pourrez créer votre liste de produits favoris et y accéder depuis votre espace personnel.
        Pour créer votre liste rendez vous sur la page <a href="index.php?ctrl=produits&task=separateItem&page=produits">"Nos Produits"</a> pour consulter tous nos stock et faire votre choix parmis beaucoup de variétés
        de fruits et légumes.</p>

</article>