<h1>Ajouter un nouvel utilisateur</h1>

<form enctype="multipart/form-data" action="index.php?ctrl=user&task=create&page=adminSpace&pageTitle=Administration" method="post" id="newUserForm">
    <fieldset>

        <div id="create_user_name" class="formDiv">
            <label for="name">Nom :</label>
            <input type="text" name="name" id="name" class="Nom" required>
        </div>

        <div id="create_user_firstname" class="formDiv">
            <label for="firstname">Prénom :</label>
            <input type="text" name="firstname" id="firstname" class="Prénom" required>
        </div>

        <div id="create_user_mail" class="formDiv">
            <label for="mail">E-mail</label>
            <input type="email" name="mail" id="mail" class="E-mail" placeholder="andre.dupont@gmail.com" required>
        </div>


        <div id="create_user_password" class="formDiv">
            <label for="password">Mot de passe</label>
            <input type="password" name="password" id="password" class="Mot de passe" placeholder="Mot de passe" minlength="8" maxlength="20" required>
        </div>

        <button class="btn btn_form newUserForm">Ajouter</button>

    </fieldset>
</form>